In [2]:
#1
import numpy as np
matrix = np.array([[10, 20, 30],  
                   [40, 50, 60],  
                   [70, 80, 90]]) 
 
# Extract top-left 2x2 submatrix 
print(matrix[0:2, 0:2])  
# Output: 
# [[10, 20], 
#  [40, 50]] 
 
# Extract the entire second column 
print(matrix[:, 1]) # Output: [20, 50, 80]

[[10 20]
 [40 50]]
[20 50 80]


In [3]:
#2
import numpy as np;
arr = np.array([10, 20, 30, 40, 50,23,21,28]) 
print(arr[[0, 2, 4]])                      # Output: [10, 30, 50] 
arr = np.array([5, 12, 18, 25, 30,21,22,27]) 
                                             # Step 1: Evaluates a True/False boolean mask 
mask = arr > 15                            # Returns: [False, False,  True,  True,  True] 
print(mask)
                                         # Step 2: Keeps values where the mask evaluates to True 
print(arr[mask])                         # Output: [18, 25, 30] 
                                        # Combine criteria using & (AND) or | (OR) 
print(arr[(arr > 10) & (arr < 30)])  # Output: [12, 18, 25]

[10 30 50]
[False False  True  True  True  True  True  True]
[18 25 30 21 22 27]
[12 18 25 21 22 27]


In [4]:
#3
import numpy as np 
# Create a sample array 
arr = np.array([10, 15, 20, 25, 30]) 
# 1. Create a boolean mask 
mask = arr > 18  # Returns: array([False, False,  True,  True,  True]) 
# 2. Apply the mask to extract values 
filtered_arr = arr[mask] # Returns: array([20, 25, 30])
print(filtered_arr)

[20 25 30]


In [5]:
#4
import numpy as np 
matrix1 = np.array([[1, 2], [3, 4]]) 
matrix2 = np.array([[5, 6]]) 
result = np.vstack((matrix1, matrix2)) 
print(result)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
35
import numpy as np 
# Shape: (2, 2) - 2 rows, 2 columns 
matrix1 = np.array([[1, 2], [3, 4]]) 
# Shape: (2, 1) - 2 rows, 1 column 
matrix2 = np.array([[5], [6]]) 
result = np.hstack((matrix1, matrix2)) 
print(result)

[[1 2 5]
 [3 4 6]]


In [8]:
#6
import numpy as np 
matrix = np.arange(16).reshape(4, 4) 
left, right = np.hsplit(matrix, 2) 
print("Left Side:\n", left) 
print("Right Side:\n", right)

Left Side:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Right Side:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [10]:
#7
import numpy as np 
matrix = np.arange(16).reshape(4, 4) 
# Cut before column index 1 and column index 3 
part1, part2, part3 = np.hsplit(matrix, [1, 3]) 
print("Part 1 (Col 0):\n", part1) 
print("Part 2 (Cols 1-2):\n", part2) 
print("Part 3 (Col 3):\n", part3)

Part 1 (Col 0):
 [[ 0]
 [ 4]
 [ 8]
 [12]]
Part 2 (Cols 1-2):
 [[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
Part 3 (Col 3):
 [[ 3]
 [ 7]
 [11]
 [15]]


In [11]:
#8
import numpy as np 
np.random.seed(42) 
sales = np.random.randint(1000, 15000, 30) 
print("Daily Sales") 
print(sales) 
print("\nTotal Sales:", sales.sum()) 
print("Average Sales:", sales.mean()) 
print("Highest Sale:", sales.max()) 
print("Lowest Sale:", sales.min()) 
best_day = np.argmax(sales)+1 
worst_day = np.argmin(sales)+1 
print("Best Sales Day:", best_day) 
print("Worst Sales Day:", worst_day) 
print("\nDays Above Average") 
print(np.where(sales > sales.mean())[0]+1)

Daily Sales
[ 8270  1860  6390 14418  6191 12964 12284  6734  7265  1466 14526  5426
  6578 12636 12363 12111  9322  2685  1769 11583 14803  7949  3433  6311
  6051  7420  2184  5555  4385 13309]

Total Sales: 238241
Average Sales: 7941.366666666667
Highest Sale: 14803
Lowest Sale: 1466
Best Sales Day: 21
Worst Sales Day: 10

Days Above Average
[ 1  4  6  7 11 14 15 16 17 20 21 22 30]


In [14]:
#9
import numpy as np 
waiting_time = np.random.randint(5,120,200) 
print("Average Waiting Time:",waiting_time.mean()) 
print("Longest Waiting:",waiting_time.max()) 
print("Patients Waiting > 60 minutes") 
print(waiting_time[waiting_time>60]) 
print("Total Patients:",waiting_time.size)

Average Waiting Time: 61.385
Longest Waiting: 119
Patients Waiting > 60 minutes
[112  93  95  63  96  64  84  66  66  66 112  68 105  77  93  64 118  94
  88  96 115  64  75  82  85 108 110  97  67  94  78  66 104  99  76  82
  91  66  89  84 113  86 115  93  64 113  69  93  75  92 112  92  67 119
  85 110 107  77  76  66  92 103 108  90  95  69 103 105  82  94 107  83
  94  81  67 100 107 117 100  98 105 107 113  75  63 119  90  70  66  61
 112  88  66  79  96  93 107  66 101  66  81 109 107  74  76]
Total Patients: 200


In [15]:
#10
import numpy as np 
np.random.seed(10) 
rides = np.random.randint(50,500,100) 
print(rides)
print("Average Daily Rides:",rides.mean()) 
print("Peak Ride Count:",rides.max()) 
print("Minimum Ride Count:",rides.min()) 
print("High Demand Days") 
print(rides[rides>400])

[315 175  65 370 419 173 206 271 463 419  58 123 306  90 470 421  66 406
 289 445 104 394 413 172 112  83 250 406 227 229 104 127  63 293 459 432
 191 398 392 336 208 139 190 371  81 363 342 333  68 143 127 456 457 144
 298 445 206 124 266 443  65  68 168 121 394 445 195 480 185 253 334 339
 300 402  94 183  54 121 394 394 356 414 232 340 410 321 394 193 184 296
 135 284 200  61 162 318 270 112 235 129]
Average Daily Rides: 259.74
Peak Ride Count: 480
Minimum Ride Count: 54
High Demand Days
[419 463 419 470 421 406 445 413 406 459 432 456 457 445 443 445 480 402
 414 410]


In [16]:
#11
import numpy as np 
salary = np.random.randint(25000,150000,500) 
print("Average Salary:",salary.mean()) 
print("Highest Salary:",salary.max()) 
print("Lowest Salary:",salary.min()) 
print("Employees earning above 1 Lakh") 
print(len(salary[salary>100000]))

Average Salary: 89677.046
Highest Salary: 149994
Lowest Salary: 25644
Employees earning above 1 Lakh
207


In [17]:
#12
import numpy as np 
temperature = np.random.randint(18,46,365) 
print("Average Temperature:",temperature.mean()) 
print("Highest Temperature:",temperature.max()) 
print("Lowest Temperature:",temperature.min()) 
print("Heat Wave Days") 
print(np.sum(temperature>40))

Average Temperature: 30.835616438356166
Highest Temperature: 45
Lowest Temperature: 18
Heat Wave Days
70


In [18]:
#13
import numpy as np 
price = np.random.randint(900,1200,250) 
print(price)
daily_change = np.diff(price) 
print("Maximum Gain:",daily_change.max()) 
print("Maximum Loss:",daily_change.min()) 
print("Average Change:",daily_change.mean())

[ 912 1010  949 1121  957  948 1017 1194 1094 1018 1092 1129  966  908
  977 1082  921 1093 1140 1187  939  942 1016  933 1148  914 1135  976
  909 1056  934 1104 1101 1063  985 1099 1037 1185  912  905  972 1084
  937 1193 1197 1146 1192 1162 1177  949  965 1081  997 1121 1014 1076
 1116 1192 1030 1192 1056 1075  919 1158 1015 1102 1145 1063 1035 1100
  992  962 1087  954  923 1034 1038 1097 1185  957 1044 1000 1138 1047
 1018 1131  919  968 1041 1049 1071 1011 1095 1198 1116 1070 1032  951
  953 1106 1137  914 1133 1099  945 1016 1018 1193  903 1093 1176  910
  962  999  954 1175 1047 1123 1143  973  999 1150 1016  901 1170 1124
  908 1142  988 1032  975 1105 1186 1149 1078 1153  979 1147  970 1083
 1040 1050 1136 1115 1001 1075 1022 1098 1035  959 1055 1040 1064  942
 1197 1184  995 1136 1157 1053 1135 1059  978 1033  914 1015 1192 1188
 1186 1046 1140  937 1181 1162 1176 1190 1011 1058 1139 1149 1069 1197
 1040 1187 1131  957  923  909  982 1180  991  990 1189  908 1096 1177
 1126 

In [25]:
#14
import numpy as np 
# Dataset Generation & Storage 
# Set random seed for reproducibility 
np.random.seed(42) 
# Generate marks for 100 students (normally distributed around 68, max 100) 
# clipped between 0 and 100 to keep it realistic 
raw_marks = np.random.normal(loc=68, scale=15, size=100) 
student_marks = np.clip(raw_marks, 0, 100).astype(int) 
# Save the dataset to a binary .npy file 
np.save("student_marks.npy", student_marks) 
print("Dataset successfully generated and saved to 'student_marks.npy'.\n") 
# --------------------------------------------------------- 
# 2. Loading & Processing (Summary Report) 
# --------------------------------------------------------- 
# Load the file back 
loaded_marks = np.load("student_marks.npy") 
# Basic calculations 
average_mark = np.mean(loaded_marks) 
highest_mark = np.max(loaded_marks) 
lowest_mark = np.min(loaded_marks) 
# Find indices/counts of students scoring above 80 
above_80_indices = np.where(loaded_marks > 80)[0] 
above_80_count = len(above_80_indices) 
# Calculate grade distribution using np.digitize or boolean indexing 
# Grades: A (>85), B (70-85), C (50-69), F (<50) 
grade_a = np.sum(loaded_marks > 85) 
grade_b = np.sum((loaded_marks >= 70) & (loaded_marks <= 85)) 
grade_c = np.sum((loaded_marks >= 50) & (loaded_marks < 70)) 
grade_f = np.sum(loaded_marks < 50) 
# --------------------------------------------------------- 
# 3. Display Summary Report 
# --------------------------------------------------------- 
print("=" * 40) 
print(" STUDENT MARKS REPORT"         
print("=" * 40) 
print(f"Total Students"      
print(f"Average Mark"        
print(f"Highest Mark "       
print(f"Lowest Mark"        
print("-" * 40) 
 ) 
: "{len(loaded_marks)}") 
: "{average_mark:.2f}") 
: "{highest_mark}") 
 : "{lowest_mark}") 
print(f"Students Scoring >80: {above_80_count}") 
print(f"Student IDs >80     : {above_80_indices.tolist()[:10]}...") # Showing first 10 IDs 
print("-" * 40) 
print("Grade Distribution:") 
print(f"  Grade A (>85)     : {grade_a}") 
print(f"  Grade B (70-85)   : {grade_b}") 
print(f"  Grade C (50-69)   : {grade_c}") 
print(f"  Grade F (<50)     
print("=" * 40)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (774858999.py, line 35)